### ISSUE TITLE
Teamviewer can't be installed by aura.

### ISSUE THREAD

**Issue by crocket** [aurapm/aura#401] opened 2016-03-10 01:29 UTC
When I try to install teamviewer with aura, I see the messages below.

```shell
% sudo aura -A teamviewer
aura >>= Determining dependencies...
aura >>= AUR Packages:
teamviewer

aura >>= Continue? [Y/n] 
aura >>= Building `teamviewer`...
aura >>= Well, building `teamviewer` failed.
aura >>= Dumping makepkg output in 3.. 2.. 1..
==> Making package: teamviewer 11.0.53191-2.3 (Thu Mar 10 10:28:20 KST 2016)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> lib32-libpng12
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.


aura >>= Would you like to continue anyway? [Y/n]
```

**Comment by theotherjimmy** [comment] 2016-03-10 01:33
The depends_x86_64 from the PKGBUILD is not being picked up as Aura currently does not understand depends_$ARCH variables. This should be fixed when we move to parsing the .SRCINFO files in stead of the PKGBUILD (read it's a planned fix) in Aura 1.4.

**Comment by crocket** [comment] 2016-03-10 01:41
It seems aura fails to install gcc-multilib required by lib32-libpng12

```shell
% sudo aura -A lib32-libpng12
aura >>= Determining dependencies...
aura >>= Dependency checking failed for these reasons:
The dependency `gcc-multilib` could not be found. You may need to search for a package to satisfy it.
```

```shell
% aura -Ai lib32-libpng12
Repository  : aur
Name        : lib32-libpng12
Version     : 1.2.56-1
AUR Status  : Up to Date
Maintainer  : arthurzam
Project URL : http://www.libpng.org/pub/png/libpng.html
AUR URL     : https://aur.archlinux.org/packages/lib32-libpng12
License     : custom
Depends On  : lib32-zlib libpng12
Build Deps  : gcc-multilib
Votes       : 237
Popularity  : 39.58
Description : A collection of routines used to create PNG format graphics files (32-bit, 1.2 branch)
```

**Comment by theotherjimmy** [comment] 2016-03-10 01:46
That's actually unrelated, as aura is not trying to build lib32-libpng12. On the other hand, I am unable to reproduce the `aura -A lib32-libpng12` problem. Have you enabled multilib?

**Comment by crocket** [comment] 2016-03-10 01:48
After enabling multilib, I could install lib32-libpng12 with aura.

**Comment by crocket** [comment] 2016-03-10 01:54
There was another problem.

```shell
% sudo aura -A teamviewer
aura >>= Determining dependencies...
aura >>= AUR Packages:
teamviewer

aura >>= Continue? [Y/n] 
aura >>= Building `teamviewer`...
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) teamviewer-11.0.53191-2.3

Total Installed Size:  183.00 MiB
Net Upgrade Size:       67.91 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                 [##################################] 100%
(1/1) checking package integrity                               [##################################] 100%
(1/1) loading package files                                    [##################################] 100%
(1/1) checking for file conflicts                              [##################################] 100%
error: failed to commit transaction (conflicting files)
teamviewer: /opt/teamviewer/config exists in filesystem
teamviewer: /opt/teamviewer/logfiles exists in filesystem
Errors occurred, no packages were upgraded.
```

**Comment by theotherjimmy** [comment] 2016-03-10 01:58
maybe you installed teamviewer before? check if a package owns those files with e.g. `aura -Qo /opt/teamviewer/config`

**Comment by crocket** [comment] 2016-03-10 02:00
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=teamviewer says `If the install fails, you need to uninstall Teamviewer 10`. I had Teamviewer 10. After uninstalling Teamviewer 10, I could install Teamviewer 11.

**Comment by fosskers** [comment] 2016-03-11 00:29
That's a fault of the `teamviewer` package.

**Comment by fosskers** [comment] 2016-03-11 00:30
Closing, as this isn't directly an Aura problem.

**Closed by fosskers** 2016-03-11 00:30 UTC
