### ISSUE TITLE
aura -M says that my package is not an aur package

### ISSUE THREAD

**Issue by PGPereira** [aurapm/aura#363] opened 2015-10-18 03:49 UTC
```
pedro@pedro ~ % sudo aura -M steam --absdeps
[sudo] senha para pedro: 
aura >>= Syncing `steam` to the local ABS Tree...
aura >>= The following are not AUR packages:
steam

aura >>= No valid packages specified.
```

It is true for any package I tried to install until now.

```
pedro@pedro ~ % sudo aura -M firefox
aura >>= Syncing `firefox` to the local ABS Tree...
aura >>= The following are not AUR packages:
firefox

aura >>= No valid packages specified.
```

**Comment by bb010g** [comment] 2015-10-19 00:15
`aura -V`?

**Comment by fosskers** [comment] 2015-10-19 00:46
I personally can't reproduce this.

**Comment by PGPereira** [comment] 2015-10-19 20:03
pedro@pedro ~ % aura -V                            
                       
 __ _ _  _ _ _ __ _    Pacman v4.2.1 - libalpm v9.0.1
/ _` | || | '_/ _` |   Copyright (C) 2006-2014 Pacman Development Team
\__,_|\_,_|_| \__,_|   Copyright (C) 2002-2006 Judd Vinet
AURA Version 1.3.2.1   
 by Colin Woodbury     Este programa pode ser redistribuído livremente sob
                       os termos da GNU General Public License
Aura Translators:      
 Chris "Kwpolska" Warrick (Polish)
 Denis Kasak / "stranac" (Croatian)
 Fredrik Haikarainen (Swedish)
 Lukas Niederbremer / Jonas Platte (German)
 Alejandro Gómez (Spanish)
 Henry "Ingvij" Kupty / Thiago "thiagowfx" Perrotta (Portuguese)
 Ma Jiehong / Fabien Dubosson (French)
 Kyrylo Silin (Russian)
 Bob Valantin (Italian)
 Filip Brcic (Serbian)
 "chinatsun" (Norwegian)
 "pak tua Greg" (Indonesia)

**Comment by fosskers** [comment] 2015-10-19 20:09
Then you have the latest version. I tried for firefox as well, and it works for me. Can you try:

`sudo aura -M firefox --auradebug`

**Comment by PGPereira** [comment] 2015-10-19 20:10
pedro@pedro ~ % sudo aura -Mt bumblebee                                                                                                                                                     :(
aura >>= Syncing `bumblebee` to the local ABS Tree...
pedro@pedro ~ % sudo aura -M firefox --auradebug
User              => root
True User         => pedro
Build User        => pedro
Using Sudo?       => Yes!
Pacman Flags      => 
Other Flags       => ABSInstall Debug
Other Input       => firefox
Language          => English
Pacman Command    => /usr/bin/powerpill
Editor            => vim
$CARCH            => x86_64
Ignored Pkgs      => 
Build Path        => /var/cache/pacman/pkg/
Pkg Cache Path    => /var/cache/pacman/pkg/
Log File Path     => /var/log/pacman.log
Quiet?            => No.
Silent Building?  => Yes!
Must Confirm?     => Yes!
Needed only?      => No.
PKGBUILD editing? => No.
Diff PKGBUILDs?   => No.
Rebuild Devel?    => No.
Use Customizepkg? => No.
Forego PowerPill? => No.
Keep source?      => No.
aura >>= Syncing `firefox` to the local ABS Tree...
aura >>= The following are not AUR packages:
firefox

aura >>= No valid packages specified.

**Comment by PGPereira** [comment] 2015-10-19 20:21
I don't know if this means anything, but I'm using the pre-compiled version from aur.

pedro@pedro ~ % env LANG=en_US.UTF-8 aura -Qi aura-bin
Name           : aura-bin
Version        : 1.3.2.1-1
Description    : A secure package manager for Arch Linux and the AUR written in Haskell - Prebuilt binary
Architecture   : x86_64
URL            : https://github.com/fosskers/aura
Licenses       : GPL-3
Groups         : None
Provides       : aura
Depends On     : gmp  pacman  pcre  abs
Optional Deps  : powerpill: For faster repository downloads. [installed]
                 customizepkg: For auto-editing of PKGBUILDs.
                 aur-git: AUR package completions for zsh.
Required By    : None
Optional For   : None
Conflicts With : aura  aura-git
Replaces       : None
Installed Size :  15,54 MiB
Packager       : Unknown Packager
Build Date     : Sáb 17 Out 2015 19:51:49 BRT
Install Date   : Sáb 17 Out 2015 19:52:24 BRT
Install Reason : Explicitly installed
Install Script : No
Validated By   : None

**Comment by fosskers** [comment] 2015-10-20 03:37
Try installing with `--no-pp`.

**Comment by PGPereira** [comment] 2015-10-20 19:15
Installing aura or executing the - M command?

**Comment by bb010g** [comment] 2015-10-20 21:46
`aura -M firefox --no-pp`

**Comment by PGPereira** [comment] 2015-10-20 22:13
pedro@pedro ~ % env LANG=en_US.UTF-8 sudo aura -M firefox --no-pp                                                                                                  :(
aura >>= Syncing `firefox` to the local ABS Tree...
aura >>= The following are not AUR packages:
firefox

aura >>= No valid packages specified.

**Comment by PGPereira** [comment] 2015-10-20 22:19
The same with auradebug flag.

pedro@pedro ~ % env LANG=en_US.UTF-8 sudo aura -M firefox --no-pp --auradebug
User              => root
True User         => pedro
Build User        => pedro
Using Sudo?       => Yes!
Pacman Flags      => 
Other Flags       => ABSInstall NoPowerPill Debug
Other Input       => firefox
Language          => English
Pacman Command    => pacman
Editor            => vim
$CARCH            => x86_64
Ignored Pkgs      => 
Build Path        => /var/cache/pacman/pkg/
Pkg Cache Path    => /var/cache/pacman/pkg/
Log File Path     => /var/log/pacman.log
Quiet?            => No.
Silent Building?  => Yes!
Must Confirm?     => Yes!
Needed only?      => No.
PKGBUILD editing? => No.
Diff PKGBUILDs?   => No.
Rebuild Devel?    => No.
Use Customizepkg? => No.
Forego PowerPill? => Yes!
Keep source?      => No.
aura >>= Syncing `firefox` to the local ABS Tree...
aura >>= The following are not AUR packages:
firefox

aura >>= No valid packages specified.

**Comment by fosskers** [comment] 2015-10-21 00:28
Are you aliasing `aura` to anything in your `.bashrc`, etc?

**Comment by PGPereira** [comment] 2015-10-21 01:56
No.
pedro@pedro ~ % cat .zshrc      
# Created by newuser for 5.1.1

autoload -U compinit promptinit
compinit
promptinit

setopt completealiases
setopt HIST_IGNORE_DUPS

ttyctl -f

**Comment by PGPereira** [comment] 2015-10-21 01:56
pedro@pedro ~ % cat .bashrc 
#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

**Comment by PGPereira** [comment] 2015-10-21 15:31
The command `aura -M` works, if this give any clue.

````
pedro@pedro ~ % sudo aura -My  
aura >>= Sync the local ABS Tree? [Y/n] Y
aura >>= Syncing local ABS Tree...
==> Starting ABS sync...
receiving file list ... done

sent 263,910 bytes  received 535,413 bytes  69,506.35 bytes/sec
total size is 18,209,501  speedup is 22.78
aura >>= No valid packages specified.
sudo aura -My  36,27s user 3,13s system 74% cpu 52,552 total
````

**Comment by PGPereira** [comment] 2015-10-23 11:29
Any new test to do?

**Comment by fosskers** [comment] 2015-10-24 03:53
Perhaps even though it's synced, Aura is somehow failing to find it in your ABS tree (or can't find the tree at all). Then it could be reporting `...is not an AUR package` mistakenly, if that's a catch-all message for failures like this.

**Comment by PGPereira** [comment] 2015-10-25 03:22
Anything that I could try to solve this?

**Comment by fosskers** [comment] 2015-10-25 03:33
I now think this is the same as #367 .

**Comment by fosskers** [comment] 2015-11-20 02:44
Okay to close this?

**Comment by PGPereira** [comment] 2015-11-21 02:00
The problem persist even with `--no-pp` flag, and I'm pretty sure that I don't have aura aliased anywhere.

**Comment by fosskers** [comment] 2015-11-21 02:11
Can you try uninstalling powerpill once, then attempting the other install?
Am 20.11.2015 18:00 schrieb "Pedro Gabriel" <notifications@github.com>:

**Comment by PGPereira** [comment] 2015-11-21 02:19
The problem persist even with powerpill uninstalled. 
````
aura >>= Syncing `firefox` to the local ABS Tree...
aura >>= The following are not AUR packages:
firefox

aura >>= No valid packages specified.
````

**Comment by jpotier** [comment] 2016-03-15 22:32
Same problem here. Cannot build packages from ABS using `sudo aura -M firefox`.
My `env LANG=en_US.UTF-8 sudo aura -M firefox --no-pp --auradebug` works though.
Actually, just `env LANG=en_US.UTF-8 sudo aura -M firefox` is enough to make it work!

My `aura -V`:
```
 __ _ _  _ _ _ __ _    Pacman v5.0.1 - libalpm v10.0.1
/ _` | || | '_/ _` |   Copyright (C) 2006-2016 Pacman Development Team
\__,_|\_,_|_| \__,_|   Copyright (C) 2002-2006 Judd Vinet
AURA Version 1.3.4     
 by Colin Woodbury     This program may be freely redistributed under
                       the terms of the GNU General Public License.
Aura Translators:      
 Chris "Kwpolska" Warrick (Polish)
 Denis Kasak / "stranac" (Croatian)
 Fredrik Haikarainen (Swedish)
 Lukas Niederbremer / Jonas Platte (German)
 Alejandro Gómez (Spanish)
 Henry "Ingvij" Kupty / Thiago "thiagowfx" Perrotta (Portuguese)
 Ma Jiehong / Fabien Dubosson (French)
 Kyrylo Silin (Russian)
 Bob Valantin (Italian)
 Filip Brcic (Serbian)
 "chinatsun" (Norwegian)
 "pak tua Greg" (Indonesia)
```
My system is not in english by default… 

Smells like a bug, install from ABS shouldn't depend on the $LANG environment variable.

**Closed** 2017-10-07 18:53 UTC

**Comment by mateusfccp** [comment] 2020-01-27 09:51
I have this issue on my freshly installed Arch system, of course with `-A`.

```
ArchPinto% sudo aura -A android-sdk --auradebug --no-pp
User              => root
True User         => mateusfccp
Build User        => mateusfccp
Using Sudo?       => Yes!
Pacman Flags      => 
Other Flags       => AURInstall Debug NoPowerPill
Other Input       => android-sdk
Language          => English
Pacman Command    => pacman
Editor            => vi
$CARCH            => x86_64
Ignored Pkgs      => 
Build Path        => /var/cache/pacman/pkg/
Pkg Cache Path    => /var/cache/pacman/pkg/
Log File Path     => /var/log/pacman.log
Quiet?            => No.
Silent Building?  => Yes!
Must Confirm?     => Yes!
Needed only?      => No.
PKGBUILD editing? => No.
Diff PKGBUILDs?   => No.
Rebuild Devel?    => No.
Use Customizepkg? => No.
Forego PowerPill? => Yes!
Keep source?      => No.
aura >>= The following are not AUR packages:
android-sdk

aura >>= No valid packages specified.
```

```
ArchPinto% aura -V
                       
 __ _ _  _ _ _ __ _    Pacman v5.2.1 - libalpm v12.0.1
/ _` | || | '_/ _` |   Copyright (C) 2006-2019 Pacman Development Team
\__,_|\_,_|_| \__,_|   Copyright (C) 2002-2006 Judd Vinet
AURA Version 1.4.0     
 by Colin Woodbury     This program may be freely redistributed under
                       the terms of the GNU General Public License.
Aura Translators:      
 Chris "Kwpolska" Warrick (Polish)
 Denis Kasak / "stranac" (Croatian)
 Fredrik Haikarainen / Daniel Beecham (Swedish)
 Lukas Niederbremer / Jonas Platte (German)
 Alejandro Gómez / Sergio Conde (Spanish)
 Henry "Ingvij" Kupty / Thiago "thiagowfx" Perrotta (Portuguese)
 Ma Jiehong / Fabien Dubosson (French)
 Kyrylo Silin (Russian)
 Bob Valantin (Italian)
 Filip Brcic (Serbian)
 "chinatsun" (Norwegian)
 "pak tua Greg" (Indonesian)
 Kai Zhang (Chinese)
```

**Comment by fosskers** [comment] 2020-01-27 14:54
@mateusfccp  If you install `2.0.x` this issue should disappear.

**Comment by mateusfccp** [comment] 2020-01-27 15:07
@fosskers I installed from `https://aur.archlinux.org/aura-bin.git`. Is this repo discontinued?

**Comment by fosskers** [comment] 2020-01-27 16:51
No, I just need to make a release.
