### ISSUE TITLE
Pacman prompt for `neovim-git` package immediately exiting; cannot use -C to install afterwards

### ISSUE THREAD

**Issue by markusgrosser** [aurapm/aura#321] opened 2015-04-17 12:57 UTC
I'm running into two issues with the [`neovim-git`](https://aur.archlinux.org/packages/neovim-git) package when using Aura:

### Updating

I encounter this issue when upgrading; it does however not happen if I downgraded it (manually) before.

```
$ sudo aura -Au
aura >>= Fetching package information...
aura >>= Comparing package versions...
aura >>= AUR Packages to upgrade:
neovim-git : 0.r3039.90bce5a-1 => 0.r3262.c1a3d28-1

aura >>= Determining dependencies...
aura >>= AUR Packages:
neovim-git

aura >>= Continue? [Y/n] y
aura >>= Building `neovim-git`...
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) neovim-git-0.r3262.c1a3d28-1

Total Installed Size:  18.14 MiB
Net Upgrade Size:      -0.10 MiB

:: Proceed with installation? [Y/n]
```

Pacman and aura both immediately exit there with exit code 1, not installing the package and not continuing with other updates (if there are any). The build was successful, and installing with `pacman -U` works flawlessly.

### Installing the built package from cache

This always happens, no matter if I want to do a normal downgrade or install the new version after the updating issue happened.
```

$ sudo aura -C neovim-git
aura >>= What version of `neovim-git` do you want?
loading packages...
error: could not open file /var/cache/pacman/pkg/: Error reading fd 6
error: '/var/cache/pacman/pkg/': cannot open package file

```
 (exit code 1)

**Comment by flamusdiu** [comment] 2015-04-17 13:56
Looks like `/var/cache/pacman/pkg/` permissions are messed up. What are the permissions on the folder?

**Comment by markusgrosser** [comment] 2015-04-17 14:28
```
$ ls -l /var/cache/pacman/
total 484
drwxr-xr-x 2 root root 491520 Apr 17 14:00 pkg
$ ls -l /var/cache/pacman/pkg/neovim-git*
-rw-r--r-- 1 markus markus 3979208 Feb 28 20:01 /var/cache/pacman/pkg/neovim-git-0.r2930.4bebdd1-1-x86_64.pkg.tar.xz
-rw-r--r-- 1 markus markus 3979940 Mar 11 17:15 /var/cache/pacman/pkg/neovim-git-0.r2979.1e6c487-1-x86_64.pkg.tar.xz
-rw-r--r-- 1 markus markus 3977052 Mar 15 14:49 /var/cache/pacman/pkg/neovim-git-0.r3001.dbe7193-1-x86_64.pkg.tar.xz
-rw-r--r-- 1 markus markus 3979064 Mar 20 15:53 /var/cache/pacman/pkg/neovim-git-0.r3039.90bce5a-1-x86_64.pkg.tar.xz
-rw-r--r-- 1 markus markus 3953952 Apr 15 15:59 /var/cache/pacman/pkg/neovim-git-0.r3258.a86193d-1-x86_64.pkg.tar.xz
-rw-r--r-- 1 markus markus 3952672 Apr 17 14:00 /var/cache/pacman/pkg/neovim-git-0.r3262.c1a3d28-1-x86_64.pkg.tar.xz
```

I highly doubt it's a problem there, since it occurs on my laptop as well (on which I definitely didn't change any permissions) and `pacman -U` works flawlessly. It also doesn't occur for any other packages.

**Comment by flamusdiu** [comment] 2015-04-18 12:58
Yeah, that looks right. I get the following when I try to install it:

```
$ sudo aura -Aaxku neovim-git 
aura >>= Fetching package information...
aura >>= Comparing package versions...
aura >>= No AUR package upgrades necessary.
aura >>= `neovim-git` has no stored PKGBUILD yet.
aura >>= Determining dependencies...
aura: fd:6: hGetContents: invalid argument (invalid byte sequence)
$ sudo aura -C neovim-git
aura >>= The following have no versions in the cache, and thus canaura: <stdout>: commitBuffer: invalid argument (invalid character)
```

Which, now I have to remember what that issue is. It's on going for some packages. @fosskers might be able to chime in. I am going to take a look around to remind myself again. AURA 2.0 can't come fast enough.

**Comment by fosskers** [comment] 2015-04-23 17:17
I've seen `invalid byte sequence` before from some users but could never reproduce it. 

@markusgrosser I just tried to build neovim-git and am seeing exactly what you are. After "successfully" building, the pacman prompt immediately drops back to shell. `-C` also dies.

Notice the following behaviour:
```
colin@ko-linux ~> sudo aura -C 
colin@ko-linux ~> sudo aura -C asdf
aura >>= The following have no versions in the cache, and thus can’t be downgraded:
asdf
```
If not arg is given, `-C` dies silently. If an invalid package is given, it tells you. Meaning with neovim, it thinks it's valid yet is dying anyway. I am puzzled.

**Comment by flamusdiu** [comment] 2015-04-23 21:31
@fosskers for the `invalid byte sequence`: I get it every once in a while with the same packages. I figured  that maybe 2.0 might fix it so I was just waiting for it.

**Comment by rmarquis** [comment] 2015-04-24 14:03
This seems to be an upstream issue, see https://github.com/neovim/neovim/issues/2377.

**Comment by fosskers** [comment] 2015-04-25 05:09
Interesting. Could this be used to inject harmful commands via the sudo'd pacman?

**Comment by rmarquis** [comment] 2015-04-25 08:06
I don't think so. It looks more like some predefined byte (extra new line?) is passed to all prompt by neovim for some reason. Nothing we can do but wait.

**Comment by fosskers** [comment] 2015-04-30 23:52
Any news?

**Comment by fwalch** [comment] 2015-05-27 14:46
This might be fixed now (neovim/neovim#2598).

**Comment by flamusdiu** [comment] 2015-05-27 17:37
```
-- Installing: /home/pacman/pkg/neovim-git11036/neovim-git/pkg/neovim-git/usr/share/locale/ga/LC_MESSAGES/nvim.mo
-- Installing: /home/pacman/pkg/neovim-git11036/neovim-git/pkg/neovim-git/usr/share/locale/it/LC_MESSAGES/nvim.mo
-- Installing: /home/pacman/pkg/neovim-git11036/neovim-git/pkg/neovim-git/usr/share/locale/ja/LC_MESSAGES/nvim.mo
-- Installing: /home/pacman/pkg/neovim-git11036/neovim-git/pkg/neovim-git/usr/share/locale/ko.UTF-8/LC_MESSAGES/nvim.mo
-- Installing: /home/pacman/pkg/neovim-git11036/neovim-git/pkg/neovim-git/usr/share/locale/nl/LC_MESSAGES/nvim.mo
-- Installing: /home/pacman/pkg/neovim-git11036/neovim-git/pkg/neovim-git/usr/share/locale/no/LC_MESSAGES/nvim.mo
-- Installing: /home/pacman/pkg/neovim-git11036/neovim-git/pkg/neovim-git/usr/share/locale/pl/LC_MESSAGES/nvim.mo
-- Installing: /home/pacman/pkg/neovim-git11036/neovim-git/pkg/neovim-git/usr/share/locale/pt_BR/LC_MESSAGES/nvim.mo
-- Installing: /home/pacman/pkg/neovim-git11036/neovim-git/pkg/neovim-git/usr/share/locale/ru/LC_MESSAGES/nvim.mo
-- Installing: /home/pacman/pkg/neovim-git11036/neovim-git/pkg/neovim-git/usr/share/locale/sk/LC_MESSAGES/nvim.mo
-- Installing: /home/pacman/pkg/neovim-git11036/neovim-git/pkg/neovim-git/usr/share/locale/sv/LC_MESSAGES/nvim.mo
-- Installing: /home/pacman/pkg/neovim-git11036/neovim-git/pkg/neovim-git/usr/share/locale/uk/LC_MESSAGES/nvim.mo
-- Installing: /home/pacman/pkg/neovim-git11036/neovim-git/pkg/neovim-git/usr/share/locale/vi/LC_MESSAGES/nvim.mo
-- Installing: /home/pacman/pkg/neovim-git11036/neovim-git/pkg/neovim-git/usr/share/locale/zh_CN/LC_MESSAGES/nvim.mo
-- Installing: /home/pacman/pkg/neovim-git11036/neovim-git/pkg/neovim-git/usr/share/locale/zh_CN.UTF-8/LC_MESSAGES/nvim.mo
-- Installing: /home/pacman/pkg/neovim-git11036/neovim-git/pkg/neovim-git/usr/share/locale/zh_TW/LC_MESSAGES/nvim.mo
-- Installing: /home/pacman/pkg/neovim-git11036/neovim-git/pkg/neovim-git/usr/share/locale/zh_TW.UTF-8/LC_MESSAGES/nvim.mo
==> Tidying install...
  -> Purging unwanted files...
  -> Removing libtool files...
  -> Removing static library files...
  -> Compressing man and info pages...
  -> Stripping unneeded symbols from binaries and libraries...
==> Creating package "neovim-git"...
  -> Generating .PKGINFO file...
  -> Adding install file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: neovim-git 0.r3522.3dd166b-1 (Wed May 27 13:20:45 EDT 2015)
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) neovim-git-0.r3522.3dd166b-1

Total Installed Size:  17.89 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                     [################################################] 100%
(1/1) checking package integrity                                                   [################################################] 100%
(1/1) loading package files                                                        [################################################] 100%
(1/1) checking for file conflicts                                                  [################################################] 100%
(1/1) checking available disk space                                                [################################################] 100%
(1/1) installing neovim-git                                                        [################################################] 100%
```
Fixed for me. Just did a complete install using `aura`

**Comment by fosskers** [comment] 2015-05-27 19:42
Great, thanks.

**Closed by fosskers** 2015-05-27 19:42 UTC
