### ISSUE TITLE
Exit with success if no packages need to be upgraded

### ISSUE THREAD

**Issue by koterpillar** [aurapm/aura#484] opened 2018-07-03 10:03 UTC
In contrast to Pacman, Aura exits with a non-zero error code when there are no packages to be upgraded. 

```shell
$ sudo pacman -Su      
:: Starting full system upgrade...
 there is nothing to do
$ echo $?                           
0
$ sudo aura -Au  
aura >>= Fetching package information...
aura >>= Comparing package versions...
aura >>= No AUR package upgrades necessary.
aura >>= No valid packages specified.
$ echo $?
1
```

There is no error here so the error code should be 0 (success).

**Comment by fosskers** [comment] 2018-07-03 15:13
Easy fix, I'll handle that around 24 hours from now.

**Comment by fosskers** [comment] 2018-07-03 15:14
Duplicate of #315 .

**Closed** 2018-07-04 15:29 UTC
