### ISSUE TITLE
Removing orphans using aura returns "error: invalid option '--sysupgrade'"

### ISSUE THREAD

**Issue by maximumultraist** [aurapm/aura#384] opened 2016-01-16 14:45 UTC
When invoking 'sudo aura -Oj', the command fails with "error: invalid option '--sysupgrade'". First observed using v1.3.4.

**Comment by fosskers** [comment] 2016-01-16 17:18
Do you have powerpill installed? Try that command again with `--auradebug`, and paste the output here.

**Comment by blinxwang** [comment] 2016-01-16 17:26
I do indeed have powerpill installed. The output is:

`User              => root
True User         => leopoldbloom
Build User        => leopoldbloom
Using Sudo?       => Yes!
Pacman Flags      => 
Other Flags       => Orphans Abandon Debug
Other Input       => 
Language          => English
Pacman Command    => /usr/bin/powerpill
Editor            => vi
$CARCH            => x86_64
Ignored Pkgs      => 
Build Path        => /var/cache/pacman/pkg/
Pkg Cache Path    => /var/cache/pacman/pkg/
Log File Path     => /var/log/pacman.log
Quiet?            => No.
Silent Building?  => Yes!
Must Confirm?     => Yes!
Needed only?      => No.
PKGBUILD editing? => No.
Diff PKGBUILDs?   => No.
Rebuild Devel?    => No.
Use Customizepkg? => No.
Forego PowerPill? => No.
Keep source?      => No.
error: invalid option '--sysupgrade'`

**Comment by fosskers** [comment] 2016-01-16 17:29
Try the `--no-pp` option as well. It turns off powerpill use if you have it installed.

**Comment by blinxwang** [comment] 2016-01-18 18:05
Ah, with `--no-pp` the `-Oj` command works as intended.

**Comment by fosskers** [comment] 2016-01-18 18:13
Great. It should really be the other way around. That some option `--pp` turns *on* use of powerpill.

**Comment by flamusdiu** [comment] 2016-01-18 21:31
+1 for that. Might keep these issues down. Though, when 2.0 comes out,
isn't PowerPill being dropped directly. Moving it to a hook?

**Comment by fosskers** [comment] 2016-01-19 02:59
Precisely.

**Comment by aspidites** [comment] 2016-01-27 20:45
Out of curiousity, is it possible to track which flags are incompatable? I was going to try my hand at putting up a PR that makes powerpill opt-in to address this, but I'm wondering if we can't also just say "If using powerpill options x, y, z should be disabled".

**Comment by flamusdiu** [comment] 2016-01-27 21:15
Not sure if it's worth do that, though. Even though 2.0 is still a bit
always, probably not completely worth it other then maybe disabling it by
default since it has so many issues.

**Comment by fosskers** [comment] 2016-01-28 23:26
@aspidites I'd say wait until I've ripped out the current flag parsing in favour of `optparse-applicative`.

**Comment by aspidites** [comment] 2016-01-29 00:19
Fair enough. Ping me when that's done, if you like.

On Thu, Jan 28, 2016 at 6:26 PM, Colin Woodbury <notifications@github.com>
wrote:

> @aspidites <https://github.com/aspidites> I'd say wait until I've ripped
> out the current flag parsing in favour of optparse-applicative.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurapm/aura/issues/384#issuecomment-176478778>.
>



-- 
Regards,
Edwin O Marshall (aspidites)
http://github.com/aspidites <https://github.com/aspidites>
http://bitbucket.org/aspidites <https://bitbucket.org/aspidites>
http://www.assembla.com/profile/aspidites?public=true

**Closed** 2018-06-27 01:09 UTC
