### ISSUE TITLE
Not all AUR dependencies are found

### ISSUE THREAD

**Issue by hackaugusto** [aurapm/aura#335] opened 2015-07-31 02:00 UTC
I was installing `aura -A docker-compose` and `aura` didn't find:

```
# sudo aura -A docker-compose
aura >>= Determining dependencies...
aura >>= Dependency checking failed for these reasons:
The dependency `python2-texttable` could not be found. You may need to search for a package to satisfy it.
# aura -As python2-texttable
# 
```

The package exists:

https://aur.archlinux.org/packages/python2-texttable/

I installed it using http://aur.sh/

This is my current version:

```
# pacman -Qs aura
local/aura-bin 1.3.2.0-1
    A secure package manager for Arch Linux and the AUR written in Haskell - Prebuilt binary
# aura --version
                       
 __ _ _  _ _ _ __ _    Pacman v4.2.1 - libalpm v9.0.1
/ _` | || | '_/ _` |   Copyright (C) 2006-2014 Pacman Development Team
\__,_|\_,_|_| \__,_|   Copyright (C) 2002-2006 Judd Vinet
AURA Version 1.3.2.0   
 by Colin Woodbury     This program may be freely redistributed under
                       the terms of the GNU General Public License.
Aura Translators:      
 Chris "Kwpolska" Warrick (Polish)
 Denis Kasak / "stranac" (Croatian)
 Fredrik Haikarainen (Swedish)
 Lukas Niederbremer / Jonas Platte (German)
 Alejandro Gómez (Spanish)
 Henry "Ingvij" Kupty / Thiago "thiagowfx" Perrotta (Portuguese)
 Ma Jiehong / Fabien Dubosson (French)
 Kyrylo Silin (Russian)
 Bob Valantin (Italian)
 Filip Brcic (Serbian)
 "chinatsun" (Norwegian)
 "pak tua Greg" (Indonesia)
```

**Comment by fosskers** [comment] 2015-08-01 19:52
As of `aura-1.3.2`, we target AUR4, not the legacy AUR.

**Comment by johntyree** [comment] 2015-08-04 18:30
So the plan is to just not have anything work?

**Comment by johntyree** [comment] 2015-08-04 18:38
(Until all package builds are migrated I mean)

**Comment by flamusdiu** [comment] 2015-08-04 21:36
@johntyree everything works for those packages migrated to AUR4. If the packages maintainers don't migrate them, then there is a good chance those packages will be lost.

**Comment by dkowis** [comment] 2015-08-21 06:06
So the missing packages, say like: https://aur.archlinux.org/packages/libappindicator-gtk2/ where the git repo links to a 404 page. That's the problem?

**Comment by dkowis** [comment] 2015-08-21 06:07
Interestingly enough, I can get a tarball of the thing, from the aur.git snapshot link on the right. Something is fishy.

**Comment by flamusdiu** [comment] 2015-08-21 14:13
@dkowis the missing page isn't the problem -- I check a number of packages and none of those links work properly. =(

**Comment by flamusdiu** [comment] 2015-08-21 14:14
Though:
```
> aura -As python2-texttable
aur/python2-texttable 0.8.3-1 (1)
    Generate a formatted text table using ASCII characters.
```

I am finding the package doing the search.

**Comment by dkowis** [comment] 2015-08-21 14:34
I'm having similar experiences. I can find the packages during searching, but then when I ask aura to install them, it tells me it's not a valid AUR package.

**Comment by flamusdiu** [comment] 2015-08-21 14:42
Well, here's my output:

```
> aura -A python2-textable
aura >>= Determining dependencies...
aura >>= AUR Packages:
python2-texttable

aura >>= Continue? [Y/n] y
aura >>= Building `python2-texttable`...
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) python2-texttable-0.8.3-1

Total Installed Size:  0.08 MiB

:: Proceed with installation? [Y/n] 
```

**Comment by fosskers** [comment] 2015-08-21 17:51
My aura is also able to find it. Closing this for now, but let me know if it comes up again.

**Closed by fosskers** 2015-08-21 17:51 UTC

**Comment by johntyree** [comment] 2015-10-27 02:43
I'm not finding all kinds of packages today. Not sure where the issue is, but `python2-textable` is one of them, as is `aura` and `aura-bin` itself. I discovered this while trying to install `qutebrowser` and `csvkit-git`, both of which are in the AUR but not found by Aura.


```
john@eleanor /scratch
$ aura -As aura
john@eleanor /scratch
$ aura --version
                       
 __ _ _  _ _ _ __ _    Pacman v4.2.1 - libalpm v9.0.1
/ _` | || | '_/ _` |   Copyright (C) 2006-2014 Pacman Development Team
\__,_|\_,_|_| \__,_|   Copyright (C) 2002-2006 Judd Vinet
AURA Version 1.3.2.0   
 by Colin Woodbury     This program may be freely redistributed under
                       the terms of the GNU General Public License.
Aura Translators:      
 Chris "Kwpolska" Warrick (Polish)
 Denis Kasak / "stranac" (Croatian)
 Fredrik Haikarainen (Swedish)
 Lukas Niederbremer / Jonas Platte (German)
 Alejandro Gómez (Spanish)
 Henry "Ingvij" Kupty / Thiago "thiagowfx" Perrotta (Portuguese)
 Ma Jiehong / Fabien Dubosson (French)
 Kyrylo Silin (Russian)
 Bob Valantin (Italian)
 Filip Brcic (Serbian)
 "chinatsun" (Norwegian)
 "pak tua Greg" (Indonesia)
```

**Comment by johntyree** [comment] 2015-10-27 02:46
Searching aur for an updated aura appears to have resolved it. `1.3.2.0` is very broken it seems.

**Comment by fosskers** [comment] 2015-10-27 05:30
Yeah, this is a known issue. `1.3.2` broke with a change in the AUR itself.
