### ISSUE TITLE
Aura incorrectly parses required package version?

### ISSUE THREAD

**Issue by sheela-na-geek** [aurapm/aura#375] opened 2015-11-10 11:03 UTC
Hi, I'm trying to install `ammonite` with aura
```
$ sudo aura -A ammonite 
aura >>= Determining dependencies...
aura >>= Dependency checking failed for these reasons:
The dependency `2.11.7` could not be found. You may need to search for a package to satisfy it.
```
[Aur page](https://aur.archlinux.org/packages/ammonite/) says that dependency is `scala>=2.11.7`. Does aura fail to parse this?

```
$ aura --version
                       
 __ _ _  _ _ _ __ _    Pacman v4.2.1 - libalpm v9.0.1
/ _` | || | '_/ _` |   Copyright (C) 2006-2014 Pacman Development Team
\__,_|\_,_|_| \__,_|   Copyright (C) 2002-2006 Judd Vinet
AURA Version 1.3.3     
 by Colin Woodbury     This program may be freely redistributed under
                       the terms of the GNU General Public License.
```

**Comment by theotherjimmy** [comment] 2015-11-10 11:13
I think this is a duplicate of #372.

**Closed** 2015-11-19 00:49 UTC
