### ISSUE TITLE
UTF-8 error during "determining dependencies" (AURA Version 1.3.2.1)

### ISSUE THREAD

**Issue by reaper-thresher** [aurapm/aura#369] opened 2015-10-28 18:49 UTC
I'm trying to build qemacs (builds fine with makepkg) and I get the following error:

    > sudo aura -Ax qemacs
    aura >>= Determining dependencies...
    aura: Cannot decode byte '\xf8': Data.Text.Internal.Encoding.streamDecodeUtf8With: Invalid UTF-8 stream

**Comment by flamusdiu** [comment] 2015-10-28 21:56
Appears you don't have your Language vars set right.

**Comment by fosskers** [comment] 2015-10-29 03:54
Yeah, you need to make sure you're in a UTF-8 locale.

**Comment by reaper-thresher** [comment] 2015-10-29 15:35
I have an UTF-8 locale:

    > locale
    LANG=en_US.UTF-8
    LC_CTYPE="en_US.UTF-8"
    LC_NUMERIC="en_US.UTF-8"
    LC_TIME="en_US.UTF-8"
    LC_COLLATE="en_US.UTF-8"
    LC_MONETARY="en_US.UTF-8"
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER="en_US.UTF-8"
    LC_NAME="en_US.UTF-8"
    LC_ADDRESS="en_US.UTF-8"
    LC_TELEPHONE="en_US.UTF-8"
    LC_MEASUREMENT="en_US.UTF-8"
    LC_IDENTIFICATION="en_US.UTF-8"
    LC_ALL=

**Comment by reaper-thresher** [comment] 2015-10-30 07:00
I think it might be the name of the maintainer:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=qemacs

**Comment by fosskers** [comment] 2015-10-30 16:56
Try `--hotedit`, take his name out of the pkgbuild, and see if you have the
same problem.
Am 30.10.2015 00:00 schrieb "reaper-thresher" <notifications@github.com>:

**Comment by reaper-thresher** [comment] 2015-10-31 21:12
I've tried, could didn't get to the editor:

    > sudo aura -Ax qemacs --hotedit
    aura >>= Determining dependencies...
    aura >>= Would you like to edit the PKGBUILD of `qemacs`? [Y/n] Y
    aura: Cannot decode byte '\xf8': Data.Text.Internal.Encoding.streamDecodeUtf8With: Invalid UTF-8 stream

**Comment by fosskers** [comment] 2015-11-01 18:00
Your locale settings match mine. What happens when you try `aura -Ap` on the package?

**Comment by fosskers** [comment] 2015-11-19 06:24
There's another package that does this: `evopop-gtk-theme-git`

**Comment by fosskers** [comment] 2015-11-19 06:30
I've made comments on the AUR packages of both those packages.

**Comment by fosskers** [comment] 2015-11-19 06:38
Closing as duplicate of #340 .

**Closed by fosskers** 2015-11-19 06:38 UTC
